/**
 * 错误码常量定义
 * 用于统一管理应用程序中的所有错误码
 */

/**
 * 用户相关错误码
 */
export const USER_ERROR_CODES = {
  NOT_FOUND: 'USER_001',
  ALREADY_EXISTS: 'USER_002',
  INVALID_CREDENTIALS: 'USER_003',
  PERMISSION_DENIED: 'USER_004',
  ACCOUNT_LOCKED: 'USER_005',
  PROFILE_INCOMPLETE: 'USER_006',
} as const

/**
 * 认证相关错误码
 */
export const AUTH_ERROR_CODES = {
  TOKEN_EXPIRED: 'AUTH_001',
  TOKEN_INVALID: 'AUTH_002',
  TOKEN_MISSING: 'AUTH_003',
  REFRESH_TOKEN_INVALID: 'AUTH_004',
  LOGIN_FAILED: 'AUTH_005',
  LOGOUT_FAILED: 'AUTH_006',
} as const

/**
 * 授权相关错误码
 */
export const AUTHORIZATION_ERROR_CODES = {
  // 认证异常
  TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
  TOKEN_FORMAT_INVALID: 'AUTH_TOKEN_FORMAT_INVALID',
  TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  TOKEN_MALFORMED: 'AUTH_TOKEN_MALFORMED',
  UNAUTHORIZED: 'AUTH_UNAUTHORIZED',

  // 权限异常
  INSUFFICIENT_ROLE: 'AUTH_INSUFFICIENT_ROLE',
  RESOURCE_ACCESS_DENIED: 'AUTH_RESOURCE_ACCESS_DENIED',
  OPERATION_NOT_ALLOWED: 'AUTH_OPERATION_NOT_ALLOWED',
  PERMISSION_DENIED: 'AUTH_PERMISSION_DENIED',

  // 通用授权异常
  GENERIC_ERROR: 'AUTH_GENERIC_ERROR',
} as const

/**
 * 验证相关错误码
 */
export const VALIDATION_ERROR_CODES = {
  REQUIRED_FIELD_MISSING: 'VAL_001',
  INVALID_FORMAT: 'VAL_002',
  VALUE_OUT_OF_RANGE: 'VAL_003',
  DUPLICATE_VALUE: 'VAL_004',
  INVALID_REFERENCE: 'VAL_005',
  CONSTRAINT_VIOLATION: 'VAL_006',
} as const

/**
 * 管道验证相关错误码
 */
export const PIPE_ERROR_CODES = {
  INT_PARSE_ERROR: 'PIPE_INT_ERROR',
  FLOAT_PARSE_ERROR: 'PIPE_FLOAT_ERROR',
  BOOL_PARSE_ERROR: 'PIPE_BOOL_ERROR',
  ARRAY_PARSE_ERROR: 'PIPE_ARRAY_ERROR',
  UUID_PARSE_ERROR: 'PIPE_UUID_ERROR',
  ENUM_PARSE_ERROR: 'PIPE_ENUM_ERROR',
  UNKNOWN_PIPE_ERROR: 'PIPE_UNKNOWN_ERROR',
} as const

/**
 * 业务规则相关错误码
 */
export const BUSINESS_ERROR_CODES = {
  RULE_VIOLATION: 'BIZ_001',
  OPERATION_NOT_ALLOWED: 'BIZ_002',
  RESOURCE_CONFLICT: 'BIZ_003',
  QUOTA_EXCEEDED: 'BIZ_004',
  DEPENDENCY_NOT_MET: 'BIZ_005',
  STATE_TRANSITION_INVALID: 'BIZ_006',
} as const

/**
 * 系统相关错误码
 */
export const SYSTEM_ERROR_CODES = {
  INTERNAL_SERVER_ERROR: 'SYS_001',
  DATABASE_ERROR: 'SYS_002',
  EXTERNAL_SERVICE_ERROR: 'SYS_003',
  CONFIGURATION_ERROR: 'SYS_004',
  NETWORK_ERROR: 'SYS_005',
  FILE_SYSTEM_ERROR: 'SYS_006',
  CACHE_ERROR: 'SYS_007',
} as const

/**
 * HTTP状态码相关错误码
 */
export const HTTP_ERROR_CODES = {
  BAD_REQUEST: 'HTTP_400',
  UNAUTHORIZED: 'HTTP_401',
  FORBIDDEN: 'HTTP_403',
  NOT_FOUND: 'HTTP_404',
  METHOD_NOT_ALLOWED: 'HTTP_405',
  CONFLICT: 'HTTP_409',
  UNPROCESSABLE_ENTITY: 'HTTP_422',
  TOO_MANY_REQUESTS: 'HTTP_429',
  INTERNAL_SERVER_ERROR: 'HTTP_500',
  BAD_GATEWAY: 'HTTP_502',
  SERVICE_UNAVAILABLE: 'HTTP_503',
  GATEWAY_TIMEOUT: 'HTTP_504',
} as const

/**
 * 所有错误码的统一导出
 */
export const ERROR_CODES = {
  USER: USER_ERROR_CODES,
  AUTH: AUTH_ERROR_CODES,
  AUTHORIZATION: AUTHORIZATION_ERROR_CODES,
  VALIDATION: VALIDATION_ERROR_CODES,
  PIPE: PIPE_ERROR_CODES,
  BUSINESS: BUSINESS_ERROR_CODES,
  SYSTEM: SYSTEM_ERROR_CODES,
  HTTP: HTTP_ERROR_CODES,
} as const

/**
 * 错误码类型定义
 */
export type UserErrorCode = typeof USER_ERROR_CODES[keyof typeof USER_ERROR_CODES]
export type AuthErrorCode = typeof AUTH_ERROR_CODES[keyof typeof AUTH_ERROR_CODES]
export type AuthorizationErrorCode = typeof AUTHORIZATION_ERROR_CODES[keyof typeof AUTHORIZATION_ERROR_CODES]
export type ValidationErrorCode = typeof VALIDATION_ERROR_CODES[keyof typeof VALIDATION_ERROR_CODES]
export type PipeErrorCode = typeof PIPE_ERROR_CODES[keyof typeof PIPE_ERROR_CODES]
export type BusinessErrorCode = typeof BUSINESS_ERROR_CODES[keyof typeof BUSINESS_ERROR_CODES]
export type SystemErrorCode = typeof SYSTEM_ERROR_CODES[keyof typeof SYSTEM_ERROR_CODES]
export type HttpErrorCode = typeof HTTP_ERROR_CODES[keyof typeof HTTP_ERROR_CODES]

export type ErrorCode
  = | UserErrorCode
    | AuthErrorCode
    | AuthorizationErrorCode
    | ValidationErrorCode
    | PipeErrorCode
    | BusinessErrorCode
    | SystemErrorCode
    | HttpErrorCode
