services:
  tem-api:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env.docker
    volumes:
      - ./logs:/app/logs
      - /etc/localtime:/etc/localtime:ro # 同步主机时间
    restart: always
    healthcheck:
      test: [CMD, wget, --quiet, --tries=1, --spider, 'http://localhost:3000/api']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
    networks:
      - tem-api-network
      
networks:
  tem-api-network:
    driver: bridge
